# Override the dataset with --dataset DoubanBook / DoubanMovie / DoubanMusic.
dataset: DoubanBook
experiment_data_root: dataset
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"
epochs: 100
train_batch_size: 4096
eval_batch_size: 2048
stopping_step: 10
