# dataset config
model: LightGCN
dataset: Alibaba-iFashion
learning_rate:  0.002
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
load_col:
    inter: [user_id, item_id, rating]
user_inter_num_interval: "[10,inf)"
item_inter_num_interval: "[10,inf)"
val_interval:
    rating: "[3,inf)"
# unused_col:
# inter: [rating]
# training and evaluation
epochs: 500
valid_metric: HIT@10
train_batch_size: 32768
eval_batch_size: 409600000