dataset: Amazon_toy
model: LightGCN
field_separator: "\t"
gpu_id: 0
reproducibility: True
seed: 2024
embedding_size: 64

#conv:lGCN, curve:0.5, learning_rate:0.0005, model:HGCF, n_layers:4, train_batch_size:131072
learning_rate: 0.0005
reg_weight: 0.01
manifold: 'hyperbolic'
scale: 0.1
curve: 0.5
margin: 0.1
stopping_step: 30
learner: 'adam'
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
load_col:
  inter: [user_id, item_id, rating]

topk: [10,20]
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"
tail_analysis: True
popularity_analysis: False
eval_step: 500
metrics: ['Recall', 'NDCG','TailPercentage','TailHit','HeadHit']
val_interval:
  rating: "[3,inf)"
epochs: 500
train_batch_size: 131072
eval_batch_size: 40960000
valid_metric: Recall@10
num_neg: 1
eval_args:
  split: {'RS': [0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: full
train_neg_sample_args: